name: Miri

on:
  push:
    branches: [ main ]
    paths:
      - 'ppmd-rust/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'ppmd-rust/**'

jobs:
  miri:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Install rust version
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly
          components: miri, rust-std
      - name: Run miri
        run: |
          cd ppmd-rust
          cargo +nightly miri test --lib encoder_7::test::ppmd7encoder_encode_decode
